### ISSUE TITLE
Magento 2.4 Compatibility

### ISSUE THREAD

**Issue by boostify-pro** [mageplaza/magento-2-backend-reindex#4]
Is this module compatible with Magento 2.4 because I installed it but can't find it in the index management menu ?

**Comment by Victor-Mageplaza** [comment]
Hi @SoCix 

I'm Victor from Mageplaza. I would like to answer your question.
I tried on my local 2.4.0 and the module working normally.
You can refer to this picture || http://prntscr.com/uvy3qu

I think you should run s:d:c command ( di compile command)
Then try again and let me know. Thank you!

Best Regards,
Victor

**Comment by SoCix** [comment]
Hi @Victor-Mageplaza 
I compiled again and it works perfectly, thank you.
