### ISSUE TITLE
Compatibility with Elasticsuite

### ISSUE THREAD

**Issue by warinetesteban** [mageplaza/magento-2-backend-reindex#5]
Hello, 

First of all, thanks for this extension. I don't install it yet and I want to know if this extension is compatible with Smile module Elasticsuite.

Regards.

**Comment by sonnb-98** [comment]
Hi,

I want to confirm for you that the Backend Reindex module is already compatible with Elasticsearch.
Please install it and let me know if you have problems.

Best Regards,
Ryan
